// Mock data for demo deployments without a database
// Used when NEXT_PUBLIC_DEMO_MODE=true

const NOW = new Date("2026-06-05T10:00:00Z");
const d = (daysAgo: number) => new Date(NOW.getTime() - daysAgo * 86400000);

export const MOCK_PROFILES = [
  { id: "p1", authUserId: "u1", fullName: "Keev Admin", email: "admin@keevhousing.com", role: "OWNER", avatarUrl: null, phone: "(212) 555-0001", status: "active", createdAt: d(365), updatedAt: d(1) },
  { id: "p2", authUserId: "u2", fullName: "Sarah Johnson", email: "manager@keevhousing.com", role: "MANAGER", avatarUrl: null, phone: "(212) 555-0002", status: "active", createdAt: d(300), updatedAt: d(2) },
  { id: "p3", authUserId: "u3", fullName: "Mike Torres", email: "staff@keevhousing.com", role: "STAFF", avatarUrl: null, phone: "(212) 555-0003", status: "active", createdAt: d(200), updatedAt: d(3) },
];

export const MOCK_CONTACTS = [
  { id: "c1", fullName: "Maria Rodriguez", email: "maria.rodriguez@email.com", phone: "(718) 555-0101", contactType: "TENANT", status: "ACTIVE", borough: "Bronx", address: "234 Grand Concourse, Bronx, NY 10451", organization: null, notes: null, createdAt: d(180), updatedAt: d(5), tenant: null, landlord: null, broker: null, caseworker: null },
  { id: "c2", fullName: "James Williams", email: "james.williams@email.com", phone: "(718) 555-0102", contactType: "TENANT", status: "ACTIVE", borough: "Brooklyn", address: "891 Atlantic Ave, Brooklyn, NY 11238", organization: null, notes: null, createdAt: d(160), updatedAt: d(3), tenant: null, landlord: null, broker: null, caseworker: null },
  { id: "c3", fullName: "Aisha Jackson", email: "aisha.jackson@email.com", phone: "(347) 555-0103", contactType: "TENANT", status: "ACTIVE", borough: "Manhattan", address: "Shelter, Manhattan", organization: null, notes: null, createdAt: d(120), updatedAt: d(1), tenant: null, landlord: null, broker: null, caseworker: null },
  { id: "c4", fullName: "Carlos Mendez", email: "carlos.mendez@email.com", phone: "(718) 555-0104", contactType: "TENANT", status: "ACTIVE", borough: "Queens", address: "1245 Junction Blvd, Queens, NY 11368", organization: null, notes: null, createdAt: d(90), updatedAt: d(7), tenant: null, landlord: null, broker: null, caseworker: null },
  { id: "c5", fullName: "Tanya Brown", email: "tanya.brown@email.com", phone: "(718) 555-0105", contactType: "TENANT", status: "ACTIVE", borough: "Staten Island", address: "400 Forest Ave, Staten Island, NY 10301", organization: null, notes: null, createdAt: d(80), updatedAt: d(4), tenant: null, landlord: null, broker: null, caseworker: null },
  { id: "c6", fullName: "David Park", email: "david.park@email.com", phone: "(646) 555-0106", contactType: "TENANT", status: "ACTIVE", borough: "Brooklyn", address: "567 Flatbush Ave, Brooklyn, NY 11225", organization: null, notes: null, createdAt: d(70), updatedAt: d(2), tenant: null, landlord: null, broker: null, caseworker: null },
  { id: "c7", fullName: "Fatima Hassan", email: "fatima.hassan@email.com", phone: "(347) 555-0107", contactType: "TENANT", status: "ACTIVE", borough: "Bronx", address: "Shelter, Bronx", organization: null, notes: null, createdAt: d(60), updatedAt: d(1), tenant: null, landlord: null, broker: null, caseworker: null },
  { id: "c8", fullName: "Robert Chen", email: "robert.chen@email.com", phone: "(212) 555-0108", contactType: "TENANT", status: "ACTIVE", borough: "Manhattan", address: "245 W 108th St, New York, NY 10025", organization: null, notes: null, createdAt: d(50), updatedAt: d(6), tenant: null, landlord: null, broker: null, caseworker: null },
  { id: "c9", fullName: "ABC Properties LLC", email: "leasing@abcproperties.com", phone: "(212) 555-0201", contactType: "LANDLORD", status: "ACTIVE", borough: "Manhattan", address: "350 Fifth Ave, New York, NY 10118", organization: "ABC Properties LLC", notes: null, createdAt: d(500), updatedAt: d(10), tenant: null, landlord: null, broker: null, caseworker: null },
  { id: "c10", fullName: "Bronx Realty Group", email: "info@bronxrealty.com", phone: "(718) 555-0202", contactType: "LANDLORD", status: "ACTIVE", borough: "Bronx", address: "1180 Morris Ave, Bronx, NY 10456", organization: "Bronx Realty Group", notes: null, createdAt: d(450), updatedAt: d(15), tenant: null, landlord: null, broker: null, caseworker: null },
  { id: "c11", fullName: "Brooklyn Heights Realty", email: "listings@bhrealty.com", phone: "(718) 555-0203", contactType: "LANDLORD", status: "ACTIVE", borough: "Brooklyn", address: "100 Montague St, Brooklyn, NY 11201", organization: "Brooklyn Heights Realty", notes: null, createdAt: d(400), updatedAt: d(20), tenant: null, landlord: null, broker: null, caseworker: null },
  { id: "c12", fullName: "Metro NYC Brokers", email: "contact@metronyc.com", phone: "(212) 555-0301", contactType: "BROKER", status: "ACTIVE", borough: "Manhattan", address: "1440 Broadway, New York, NY 10018", organization: "Metro NYC Brokers", notes: null, createdAt: d(300), updatedAt: d(5), tenant: null, landlord: null, broker: null, caseworker: null },
  { id: "c13", fullName: "Queens Housing Connect", email: "info@queenshousing.com", phone: "(718) 555-0302", contactType: "BROKER", status: "ACTIVE", borough: "Queens", address: "89-00 Sutphin Blvd, Jamaica, NY 11435", organization: "Queens Housing Connect", notes: null, createdAt: d(250), updatedAt: d(8), tenant: null, landlord: null, broker: null, caseworker: null },
  { id: "c14", fullName: "Dr. Patricia Wells", email: "p.wells@hhs.nyc.gov", phone: "(212) 555-0401", contactType: "CASEWORKER", status: "ACTIVE", borough: "Manhattan", address: "250 Church St, New York, NY 10013", organization: "NYC HRA", notes: null, createdAt: d(200), updatedAt: d(3), tenant: null, landlord: null, broker: null, caseworker: null },
  { id: "c15", fullName: "Marcus Thompson", email: "m.thompson@hhs.nyc.gov", phone: "(718) 555-0402", contactType: "CASEWORKER", status: "ACTIVE", borough: "Bronx", address: "1780 Grand Concourse, Bronx, NY 10457", organization: "NYC HRA", notes: null, createdAt: d(150), updatedAt: d(6), tenant: null, landlord: null, broker: null, caseworker: null },
];

export const MOCK_LANDLORDS = [
  { id: "ll1", contactId: "c9", licenseNumber: "LL-001", totalUnits: 45, voucherFriendly: true, activeListings: 3, createdAt: d(500), updatedAt: d(10), contact: MOCK_CONTACTS[8] },
  { id: "ll2", contactId: "c10", licenseNumber: "LL-002", totalUnits: 30, voucherFriendly: true, activeListings: 2, createdAt: d(450), updatedAt: d(15), contact: MOCK_CONTACTS[9] },
  { id: "ll3", contactId: "c11", licenseNumber: "LL-003", totalUnits: 22, voucherFriendly: false, activeListings: 1, createdAt: d(400), updatedAt: d(20), contact: MOCK_CONTACTS[10] },
];

export const MOCK_BROKERS = [
  { id: "br1", contactId: "c12", licenseNumber: "BR-001", agency: "Metro NYC Brokers", activeListings: 5, createdAt: d(300), updatedAt: d(5), contact: MOCK_CONTACTS[11] },
  { id: "br2", contactId: "c13", licenseNumber: "BR-002", agency: "Queens Housing Connect", activeListings: 3, createdAt: d(250), updatedAt: d(8), contact: MOCK_CONTACTS[12] },
];

export const MOCK_CASEWORKERS = [
  { id: "cw1", contactId: "c14", agencyName: "NYC HRA", caseloadSize: 25, createdAt: d(200), updatedAt: d(3), contact: MOCK_CONTACTS[13] },
  { id: "cw2", contactId: "c15", agencyName: "NYC HRA", caseloadSize: 18, createdAt: d(150), updatedAt: d(6), contact: MOCK_CONTACTS[14] },
];

export const MOCK_TENANTS = [
  { id: "t1", contactId: "c1", tenantStatus: "SEARCHING", urgencyLevel: "HIGH", voucherType: "Section 8", voucherSize: 2, maxRent: 2400, preferredBoroughs: ["Bronx", "Manhattan"], documentsComplete: true, assignedCaseworkerId: "cw1", createdAt: d(180), updatedAt: d(5), contact: MOCK_CONTACTS[0], assignedCaseworker: { ...MOCK_CASEWORKERS[0], contact: MOCK_CONTACTS[13] } },
  { id: "t2", contactId: "c2", tenantStatus: "SEARCHING", urgencyLevel: "CRITICAL", voucherType: "CityFHEPS", voucherSize: 3, maxRent: 3200, preferredBoroughs: ["Brooklyn", "Queens"], documentsComplete: false, assignedCaseworkerId: "cw2", createdAt: d(160), updatedAt: d(3), contact: MOCK_CONTACTS[1], assignedCaseworker: { ...MOCK_CASEWORKERS[1], contact: MOCK_CONTACTS[14] } },
  { id: "t3", contactId: "c3", tenantStatus: "SEARCHING", urgencyLevel: "CRITICAL", voucherType: "HASA", voucherSize: 1, maxRent: 1800, preferredBoroughs: ["Manhattan", "Bronx"], documentsComplete: false, assignedCaseworkerId: "cw1", createdAt: d(120), updatedAt: d(1), contact: MOCK_CONTACTS[2], assignedCaseworker: { ...MOCK_CASEWORKERS[0], contact: MOCK_CONTACTS[13] } },
  { id: "t4", contactId: "c4", tenantStatus: "SEARCHING", urgencyLevel: "MEDIUM", voucherType: "HCV", voucherSize: 2, maxRent: 2200, preferredBoroughs: ["Queens"], documentsComplete: true, assignedCaseworkerId: "cw2", createdAt: d(90), updatedAt: d(7), contact: MOCK_CONTACTS[3], assignedCaseworker: { ...MOCK_CASEWORKERS[1], contact: MOCK_CONTACTS[14] } },
  { id: "t5", contactId: "c5", tenantStatus: "HOUSED", urgencyLevel: "LOW", voucherType: "FHEPS", voucherSize: 2, maxRent: 2600, preferredBoroughs: ["Staten Island", "Brooklyn"], documentsComplete: true, assignedCaseworkerId: null, createdAt: d(80), updatedAt: d(4), contact: MOCK_CONTACTS[4], assignedCaseworker: null },
  { id: "t6", contactId: "c6", tenantStatus: "SEARCHING", urgencyLevel: "HIGH", voucherType: "Section 8", voucherSize: 3, maxRent: 2900, preferredBoroughs: ["Brooklyn"], documentsComplete: true, assignedCaseworkerId: "cw1", createdAt: d(70), updatedAt: d(2), contact: MOCK_CONTACTS[5], assignedCaseworker: { ...MOCK_CASEWORKERS[0], contact: MOCK_CONTACTS[13] } },
  { id: "t7", contactId: "c7", tenantStatus: "SEARCHING", urgencyLevel: "CRITICAL", voucherType: "CityFHEPS", voucherSize: 1, maxRent: 1600, preferredBoroughs: ["Bronx", "Manhattan"], documentsComplete: false, assignedCaseworkerId: "cw2", createdAt: d(60), updatedAt: d(1), contact: MOCK_CONTACTS[6], assignedCaseworker: { ...MOCK_CASEWORKERS[1], contact: MOCK_CONTACTS[14] } },
  { id: "t8", contactId: "c8", tenantStatus: "LEASE_SIGNED", urgencyLevel: "LOW", voucherType: "HCV", voucherSize: 2, maxRent: 2800, preferredBoroughs: ["Manhattan"], documentsComplete: true, assignedCaseworkerId: "cw1", createdAt: d(50), updatedAt: d(6), contact: MOCK_CONTACTS[7], assignedCaseworker: { ...MOCK_CASEWORKERS[0], contact: MOCK_CONTACTS[13] } },
];

export const MOCK_PROPERTIES = [
  { id: "pr1", address: "1450 Grand Concourse", borough: "Bronx", neighborhood: "Highbridge", propertyName: "Grand Concourse Apts", bedrooms: 2, bathrooms: 1, rent: 2200, status: "AVAILABLE", voucherAccepted: true, landlordId: "ll2", brokerId: null, amenities: ["Laundry", "Heat Included"], yearBuilt: 1965, sqft: 850, createdAt: d(400), updatedAt: d(5), landlord: { ...MOCK_LANDLORDS[1], contact: MOCK_CONTACTS[9] }, broker: null },
  { id: "pr2", address: "789 Eastern Pkwy", borough: "Brooklyn", neighborhood: "Crown Heights", propertyName: null, bedrooms: 3, bathrooms: 2, rent: 2800, status: "AVAILABLE", voucherAccepted: true, landlordId: "ll3", brokerId: "br1", amenities: ["Dishwasher", "Elevator"], yearBuilt: 1978, sqft: 1100, createdAt: d(350), updatedAt: d(3), landlord: { ...MOCK_LANDLORDS[2], contact: MOCK_CONTACTS[10] }, broker: { ...MOCK_BROKERS[0], contact: MOCK_CONTACTS[11] } },
  { id: "pr3", address: "245 W 108th St #4A", borough: "Manhattan", neighborhood: "Manhattan Valley", propertyName: null, bedrooms: 2, bathrooms: 1, rent: 2600, status: "OCCUPIED", voucherAccepted: true, landlordId: "ll1", brokerId: null, amenities: ["Doorman", "Gym"], yearBuilt: 1955, sqft: 900, createdAt: d(300), updatedAt: d(10), landlord: { ...MOCK_LANDLORDS[0], contact: MOCK_CONTACTS[8] }, broker: null },
  { id: "pr4", address: "1245 Junction Blvd #2B", borough: "Queens", neighborhood: "Corona", propertyName: "Junction Heights", bedrooms: 2, bathrooms: 1, rent: 2100, status: "AVAILABLE", voucherAccepted: true, landlordId: "ll1", brokerId: "br2", amenities: ["Parking", "Backyard"], yearBuilt: 1970, sqft: 800, createdAt: d(280), updatedAt: d(7), landlord: { ...MOCK_LANDLORDS[0], contact: MOCK_CONTACTS[8] }, broker: { ...MOCK_BROKERS[1], contact: MOCK_CONTACTS[12] } },
  { id: "pr5", address: "400 Forest Ave #3C", borough: "Staten Island", neighborhood: "West Brighton", propertyName: null, bedrooms: 2, bathrooms: 1, rent: 1900, status: "OCCUPIED", voucherAccepted: true, landlordId: "ll2", brokerId: null, amenities: ["Laundry", "Storage"], yearBuilt: 1962, sqft: 750, createdAt: d(260), updatedAt: d(12), landlord: { ...MOCK_LANDLORDS[1], contact: MOCK_CONTACTS[9] }, broker: null },
  { id: "pr6", address: "567 Flatbush Ave #1F", borough: "Brooklyn", neighborhood: "Flatbush", propertyName: "Flatbush Gardens", bedrooms: 3, bathrooms: 2, rent: 3100, status: "AVAILABLE", voucherAccepted: true, landlordId: "ll3", brokerId: "br1", amenities: ["Elevator", "Package Room"], yearBuilt: 1985, sqft: 1200, createdAt: d(240), updatedAt: d(4), landlord: { ...MOCK_LANDLORDS[2], contact: MOCK_CONTACTS[10] }, broker: { ...MOCK_BROKERS[0], contact: MOCK_CONTACTS[11] } },
  { id: "pr7", address: "891 Atlantic Ave #5D", borough: "Brooklyn", neighborhood: "Boerum Hill", propertyName: null, bedrooms: 1, bathrooms: 1, rent: 2400, status: "PENDING", voucherAccepted: false, landlordId: "ll1", brokerId: null, amenities: ["Roof Deck", "Intercom"], yearBuilt: 1992, sqft: 650, createdAt: d(220), updatedAt: d(2), landlord: { ...MOCK_LANDLORDS[0], contact: MOCK_CONTACTS[8] }, broker: null },
  { id: "pr8", address: "234 Grand Concourse #7A", borough: "Bronx", neighborhood: "Morrisania", propertyName: "Morrisania Plaza", bedrooms: 2, bathrooms: 1, rent: 2050, status: "AVAILABLE", voucherAccepted: true, landlordId: "ll2", brokerId: null, amenities: ["Laundry", "Bike Storage"], yearBuilt: 1958, sqft: 820, createdAt: d(200), updatedAt: d(8), landlord: { ...MOCK_LANDLORDS[1], contact: MOCK_CONTACTS[9] }, broker: null },
  { id: "pr9", address: "145 East 92nd St #6B", borough: "Manhattan", neighborhood: "Carnegie Hill", propertyName: null, bedrooms: 1, bathrooms: 1, rent: 2900, status: "AVAILABLE", voucherAccepted: false, landlordId: "ll1", brokerId: "br1", amenities: ["Doorman", "Gym", "Concierge"], yearBuilt: 2001, sqft: 700, createdAt: d(180), updatedAt: d(6), landlord: { ...MOCK_LANDLORDS[0], contact: MOCK_CONTACTS[8] }, broker: { ...MOCK_BROKERS[0], contact: MOCK_CONTACTS[11] } },
  { id: "pr10", address: "89-12 Sutphin Blvd #3A", borough: "Queens", neighborhood: "Jamaica", propertyName: "Jamaica Towers", bedrooms: 3, bathrooms: 2, rent: 2700, status: "AVAILABLE", voucherAccepted: true, landlordId: "ll2", brokerId: "br2", amenities: ["Parking", "Laundry", "A/C"], yearBuilt: 1975, sqft: 1050, createdAt: d(160), updatedAt: d(3), landlord: { ...MOCK_LANDLORDS[1], contact: MOCK_CONTACTS[9] }, broker: { ...MOCK_BROKERS[1], contact: MOCK_CONTACTS[12] } },
  { id: "pr11", address: "1780 Grand Concourse #2C", borough: "Bronx", neighborhood: "Fordham", propertyName: null, bedrooms: 1, bathrooms: 1, rent: 1800, status: "AVAILABLE", voucherAccepted: true, landlordId: "ll2", brokerId: null, amenities: ["Near Transit", "Heat Included"], yearBuilt: 1968, sqft: 600, createdAt: d(140), updatedAt: d(9), landlord: { ...MOCK_LANDLORDS[1], contact: MOCK_CONTACTS[9] }, broker: null },
  { id: "pr12", address: "325 Wyckoff Ave #4E", borough: "Brooklyn", neighborhood: "Bushwick", propertyName: "Bushwick Commons", bedrooms: 2, bathrooms: 1, rent: 2350, status: "OCCUPIED", voucherAccepted: true, landlordId: "ll3", brokerId: null, amenities: ["Laundry", "Backyard"], yearBuilt: 1971, sqft: 880, createdAt: d(120), updatedAt: d(11), landlord: { ...MOCK_LANDLORDS[2], contact: MOCK_CONTACTS[10] }, broker: null },
];

export const MOCK_CASES = [
  { id: "cs1", caseNumber: "CASE-2026-001", tenantId: "t2", propertyId: null, status: "SEARCHING", priority: "CRITICAL", caseSummary: "Family of 4 facing eviction, needs 3BR unit in Brooklyn or Queens. CityFHEPS voucher approved.", nextFollowUpDate: new Date(NOW.getTime() + 2 * 86400000), assignedStaffId: "p2", assignedStaff: { fullName: "Sarah Johnson", avatarUrl: null }, createdAt: d(160), updatedAt: d(3), tenant: { ...MOCK_TENANTS[1], contact: MOCK_CONTACTS[1] }, property: null, landlord: null, broker: null, caseworker: { ...MOCK_CASEWORKERS[1], contact: MOCK_CONTACTS[14] } },
  { id: "cs2", caseNumber: "CASE-2026-002", tenantId: "t3", propertyId: null, status: "NEW", priority: "CRITICAL", caseSummary: "Single adult in DHS shelter, HASA voucher. Medical accommodations needed.", nextFollowUpDate: new Date(NOW.getTime() + 1 * 86400000), assignedStaffId: "p3", assignedStaff: { fullName: "Mike Torres", avatarUrl: null }, createdAt: d(120), updatedAt: d(1), tenant: { ...MOCK_TENANTS[2], contact: MOCK_CONTACTS[2] }, property: null, landlord: null, broker: null, caseworker: { ...MOCK_CASEWORKERS[0], contact: MOCK_CONTACTS[13] } },
  { id: "cs3", caseNumber: "CASE-2026-003", tenantId: "t1", propertyId: "pr1", status: "VIEWING_SCHEDULED", priority: "HIGH", caseSummary: "Maria viewing 2BR in Bronx, Section 8 approved. Scheduled for Thursday.", nextFollowUpDate: new Date(NOW.getTime() + 3 * 86400000), assignedStaffId: "p2", assignedStaff: { fullName: "Sarah Johnson", avatarUrl: null }, createdAt: d(180), updatedAt: d(5), tenant: { ...MOCK_TENANTS[0], contact: MOCK_CONTACTS[0] }, property: MOCK_PROPERTIES[0], landlord: null, broker: null, caseworker: { ...MOCK_CASEWORKERS[0], contact: MOCK_CONTACTS[13] } },
  { id: "cs4", caseNumber: "CASE-2026-004", tenantId: "t7", propertyId: null, status: "NEW", priority: "CRITICAL", caseSummary: "Fatima in emergency shelter, CityFHEPS voucher, needs 1BR urgently.", nextFollowUpDate: new Date(NOW.getTime() + 1 * 86400000), assignedStaffId: "p3", assignedStaff: { fullName: "Mike Torres", avatarUrl: null }, createdAt: d(60), updatedAt: d(1), tenant: { ...MOCK_TENANTS[6], contact: MOCK_CONTACTS[6] }, property: null, landlord: null, broker: null, caseworker: { ...MOCK_CASEWORKERS[1], contact: MOCK_CONTACTS[14] } },
  { id: "cs5", caseNumber: "CASE-2026-005", tenantId: "t6", propertyId: "pr6", status: "APPLICATION_STARTED", priority: "HIGH", caseSummary: "David applied for 3BR in Flatbush. Awaiting landlord approval. Documents submitted.", nextFollowUpDate: new Date(NOW.getTime() + 5 * 86400000), assignedStaffId: "p2", assignedStaff: { fullName: "Sarah Johnson", avatarUrl: null }, createdAt: d(70), updatedAt: d(2), tenant: { ...MOCK_TENANTS[5], contact: MOCK_CONTACTS[5] }, property: MOCK_PROPERTIES[5], landlord: null, broker: null, caseworker: { ...MOCK_CASEWORKERS[0], contact: MOCK_CONTACTS[13] } },
  { id: "cs6", caseNumber: "CASE-2026-006", tenantId: "t4", propertyId: "pr4", status: "VIEWING_SCHEDULED", priority: "MEDIUM", caseSummary: "Carlos viewing 2BR in Corona. HCV voucher, needs walkthrough.", nextFollowUpDate: new Date(NOW.getTime() + 7 * 86400000), assignedStaffId: "p3", assignedStaff: { fullName: "Mike Torres", avatarUrl: null }, createdAt: d(90), updatedAt: d(7), tenant: { ...MOCK_TENANTS[3], contact: MOCK_CONTACTS[3] }, property: MOCK_PROPERTIES[3], landlord: null, broker: null, caseworker: { ...MOCK_CASEWORKERS[1], contact: MOCK_CONTACTS[14] } },
  { id: "cs7", caseNumber: "CASE-2026-007", tenantId: "t8", propertyId: "pr3", status: "LEASE_SIGNING", priority: "LOW", caseSummary: "Robert signing lease at 245 W 108th St. HCV approved, moving in next month.", nextFollowUpDate: new Date(NOW.getTime() + 4 * 86400000), assignedStaffId: "p2", assignedStaff: { fullName: "Sarah Johnson", avatarUrl: null }, createdAt: d(50), updatedAt: d(6), tenant: { ...MOCK_TENANTS[7], contact: MOCK_CONTACTS[7] }, property: MOCK_PROPERTIES[2], landlord: null, broker: null, caseworker: { ...MOCK_CASEWORKERS[0], contact: MOCK_CONTACTS[13] } },
  { id: "cs8", caseNumber: "CASE-2026-008", tenantId: "t5", propertyId: "pr5", status: "HOUSED", priority: "LOW", caseSummary: "Tanya successfully housed at Forest Ave. FHEPS voucher used. Closed.", nextFollowUpDate: null, assignedStaffId: "p2", assignedStaff: { fullName: "Sarah Johnson", avatarUrl: null }, createdAt: d(80), updatedAt: d(4), tenant: { ...MOCK_TENANTS[4], contact: MOCK_CONTACTS[4] }, property: MOCK_PROPERTIES[4], landlord: null, broker: null, caseworker: null },
  { id: "cs9", caseNumber: "CASE-2026-009", tenantId: "t1", propertyId: "pr8", status: "SEARCHING", priority: "HIGH", caseSummary: "Second active search for Maria — evaluating Morrisania Plaza option.", nextFollowUpDate: new Date(NOW.getTime() + 6 * 86400000), assignedStaffId: "p3", assignedStaff: { fullName: "Mike Torres", avatarUrl: null }, createdAt: d(30), updatedAt: d(2), tenant: { ...MOCK_TENANTS[0], contact: MOCK_CONTACTS[0] }, property: MOCK_PROPERTIES[7], landlord: null, broker: null, caseworker: null },
  { id: "cs10", caseNumber: "CASE-2026-010", tenantId: "t6", propertyId: null, status: "CLOSED", priority: "MEDIUM", caseSummary: "Prior case for David — closed due to unit falling through.", nextFollowUpDate: null, assignedStaffId: "p2", assignedStaff: { fullName: "Sarah Johnson", avatarUrl: null }, createdAt: d(100), updatedAt: d(30), tenant: { ...MOCK_TENANTS[5], contact: MOCK_CONTACTS[5] }, property: null, landlord: null, broker: null, caseworker: null },
];

export const MOCK_TASKS = [
  { id: "tk1", title: "Schedule viewing — 1450 Grand Concourse", status: "PENDING", priority: "HIGH", dueDate: new Date(NOW.getTime() + 2 * 86400000), assignedToId: "p2", assignedTo: { fullName: "Sarah Johnson", avatarUrl: null }, relatedCaseId: "cs3", relatedCase: { caseNumber: "CASE-2026-003" }, relatedContactId: "c1", relatedContact: { fullName: "Maria Rodriguez" }, relatedPropertyId: "pr1", relatedProperty: { address: "1450 Grand Concourse", borough: "Bronx" }, description: "Confirm viewing with landlord and tenant.", createdAt: d(10), updatedAt: d(1) },
  { id: "tk2", title: "Collect missing documents — James Williams", status: "PENDING", priority: "CRITICAL", dueDate: new Date(NOW.getTime() + 1 * 86400000), assignedToId: "p3", assignedTo: { fullName: "Mike Torres", avatarUrl: null }, relatedCaseId: "cs1", relatedCase: { caseNumber: "CASE-2026-001" }, relatedContactId: "c2", relatedContact: { fullName: "James Williams" }, relatedPropertyId: null, relatedProperty: null, description: "Birth certificates and income verification still outstanding.", createdAt: d(8), updatedAt: d(1) },
  { id: "tk3", title: "Submit HQS inspection request — pr4", status: "IN_PROGRESS", priority: "HIGH", dueDate: new Date(NOW.getTime() + 3 * 86400000), assignedToId: "p2", assignedTo: { fullName: "Sarah Johnson", avatarUrl: null }, relatedCaseId: "cs6", relatedCase: { caseNumber: "CASE-2026-006" }, relatedContactId: null, relatedContact: null, relatedPropertyId: "pr4", relatedProperty: { address: "1245 Junction Blvd #2B", borough: "Queens" }, description: "File HQS inspection with HPD.", createdAt: d(6), updatedAt: d(2) },
  { id: "tk4", title: "Follow up with NYC HRA — Fatima Hassan", status: "PENDING", priority: "CRITICAL", dueDate: new Date(NOW.getTime() + 0.5 * 86400000), assignedToId: "p3", assignedTo: { fullName: "Mike Torres", avatarUrl: null }, relatedCaseId: "cs4", relatedCase: { caseNumber: "CASE-2026-004" }, relatedContactId: "c7", relatedContact: { fullName: "Fatima Hassan" }, relatedPropertyId: null, relatedProperty: null, description: "Confirm CityFHEPS voucher validity.", createdAt: d(5), updatedAt: d(1) },
  { id: "tk5", title: "Prepare lease signing packet — Robert Chen", status: "IN_PROGRESS", priority: "MEDIUM", dueDate: new Date(NOW.getTime() + 4 * 86400000), assignedToId: "p2", assignedTo: { fullName: "Sarah Johnson", avatarUrl: null }, relatedCaseId: "cs7", relatedCase: { caseNumber: "CASE-2026-007" }, relatedContactId: "c8", relatedContact: { fullName: "Robert Chen" }, relatedPropertyId: "pr3", relatedProperty: { address: "245 W 108th St #4A", borough: "Manhattan" }, description: "Print and organize lease, HAP contract, rider.", createdAt: d(7), updatedAt: d(3) },
  { id: "tk6", title: "Reach out to 5 new landlords this week", status: "PENDING", priority: "MEDIUM", dueDate: new Date(NOW.getTime() + 5 * 86400000), assignedToId: "p3", assignedTo: { fullName: "Mike Torres", avatarUrl: null }, relatedCaseId: null, relatedCase: null, relatedContactId: null, relatedContact: null, relatedPropertyId: null, relatedProperty: null, description: "Expand voucher-friendly landlord network in Queens.", createdAt: d(4), updatedAt: d(1) },
  { id: "tk7", title: "Update Aisha Jackson case notes", status: "OVERDUE", priority: "HIGH", dueDate: d(2), assignedToId: "p3", assignedTo: { fullName: "Mike Torres", avatarUrl: null }, relatedCaseId: "cs2", relatedCase: { caseNumber: "CASE-2026-002" }, relatedContactId: "c3", relatedContact: { fullName: "Aisha Jackson" }, relatedPropertyId: null, relatedProperty: null, description: "Document shelter case worker meeting.", createdAt: d(10), updatedAt: d(5) },
  { id: "tk8", title: "Monthly report — June 2026", status: "PENDING", priority: "LOW", dueDate: new Date(NOW.getTime() + 25 * 86400000), assignedToId: "p1", assignedTo: { fullName: "Keev Admin", avatarUrl: null }, relatedCaseId: null, relatedCase: null, relatedContactId: null, relatedContact: null, relatedPropertyId: null, relatedProperty: null, description: "Compile housing placements and outcomes for June.", createdAt: d(3), updatedAt: d(1) },
];

export const MOCK_ACTIVITY = [
  { id: "a1", action: "CASE_UPDATED", entityType: "HousingCase", entityId: "cs3", description: "Case CASE-2026-003 moved to VIEWING status", actorId: "p2", actor: { fullName: "Sarah Johnson", avatarUrl: null }, metadata: {}, createdAt: d(0.1) },
  { id: "a2", action: "TASK_CREATED", entityType: "Task", entityId: "tk1", description: "New task: Schedule viewing — 1450 Grand Concourse", actorId: "p2", actor: { fullName: "Sarah Johnson", avatarUrl: null }, metadata: {}, createdAt: d(0.2) },
  { id: "a3", action: "CONTACT_CREATED", entityType: "Contact", entityId: "c7", description: "New contact added: Fatima Hassan (TENANT)", actorId: "p3", actor: { fullName: "Mike Torres", avatarUrl: null }, metadata: {}, createdAt: d(0.5) },
  { id: "a4", action: "CASE_CREATED", entityType: "HousingCase", entityId: "cs4", description: "New case opened: CASE-2026-004 for Fatima Hassan", actorId: "p3", actor: { fullName: "Mike Torres", avatarUrl: null }, metadata: {}, createdAt: d(1) },
  { id: "a5", action: "DOCUMENT_UPLOADED", entityType: "Document", entityId: "doc1", description: "CityFHEPS voucher uploaded for James Williams", actorId: "p2", actor: { fullName: "Sarah Johnson", avatarUrl: null }, metadata: {}, createdAt: d(1.5) },
  { id: "a6", action: "CASE_UPDATED", entityType: "HousingCase", entityId: "cs5", description: "Case CASE-2026-005 moved to APPLICATION status", actorId: "p2", actor: { fullName: "Sarah Johnson", avatarUrl: null }, metadata: {}, createdAt: d(2) },
  { id: "a7", action: "PROPERTY_UPDATED", entityType: "Property", entityId: "pr6", description: "Property 567 Flatbush Ave marked as AVAILABLE", actorId: "p1", actor: { fullName: "Keev Admin", avatarUrl: null }, metadata: {}, createdAt: d(2.5) },
  { id: "a8", action: "TASK_COMPLETED", entityType: "Task", entityId: "tk5", description: "Task completed: Submit lease docs for Robert Chen", actorId: "p2", actor: { fullName: "Sarah Johnson", avatarUrl: null }, metadata: {}, createdAt: d(3) },
  { id: "a9", action: "NOTE_ADDED", entityType: "Note", entityId: "n1", description: "Note added to CASE-2026-002 by Mike Torres", actorId: "p3", actor: { fullName: "Mike Torres", avatarUrl: null }, metadata: {}, createdAt: d(3.5) },
  { id: "a10", action: "TENANT_UPDATED", entityType: "Tenant", entityId: "t5", description: "Tanya Brown status updated to HOUSED", actorId: "p2", actor: { fullName: "Sarah Johnson", avatarUrl: null }, metadata: {}, createdAt: d(4) },
  { id: "a11", action: "CASE_UPDATED", entityType: "HousingCase", entityId: "cs7", description: "Case CASE-2026-007 moved to LEASE_SIGNING", actorId: "p2", actor: { fullName: "Sarah Johnson", avatarUrl: null }, metadata: {}, createdAt: d(5) },
  { id: "a12", action: "CONTACT_UPDATED", entityType: "Contact", entityId: "c6", description: "David Park documents marked complete", actorId: "p3", actor: { fullName: "Mike Torres", avatarUrl: null }, metadata: {}, createdAt: d(6) },
  { id: "a13", action: "PROPERTY_CREATED", entityType: "Property", entityId: "pr11", description: "New property listed: 1780 Grand Concourse #2C, Bronx", actorId: "p1", actor: { fullName: "Keev Admin", avatarUrl: null }, metadata: {}, createdAt: d(7) },
  { id: "a14", action: "TASK_CREATED", entityType: "Task", entityId: "tk2", description: "Task created: Collect missing documents — James Williams", actorId: "p2", actor: { fullName: "Sarah Johnson", avatarUrl: null }, metadata: {}, createdAt: d(8) },
  { id: "a15", action: "CASE_CREATED", entityType: "HousingCase", entityId: "cs9", description: "New case opened: CASE-2026-009 for Maria Rodriguez", actorId: "p3", actor: { fullName: "Mike Torres", avatarUrl: null }, metadata: {}, createdAt: d(9) },
];

export const MOCK_DOCUMENTS = [
  { id: "doc1", fileName: "james_williams_cityfheps_voucher.pdf", documentType: "VOUCHER", fileSize: 245000, mimeType: "application/pdf", fileUrl: "#", uploadedAt: d(1.5), relatedCaseId: "cs1", relatedCase: { caseNumber: "CASE-2026-001" }, relatedPropertyId: null, relatedProperty: null, relatedContactId: "c2", relatedContact: { fullName: "James Williams" }, relatedTenantId: null, relatedTenant: null },
  { id: "doc2", fileName: "maria_rodriguez_section8_cert.pdf", documentType: "VOUCHER", fileSize: 198000, mimeType: "application/pdf", fileUrl: "#", uploadedAt: d(5), relatedCaseId: "cs3", relatedCase: { caseNumber: "CASE-2026-003" }, relatedPropertyId: null, relatedProperty: null, relatedContactId: "c1", relatedContact: { fullName: "Maria Rodriguez" }, relatedTenantId: null, relatedTenant: null },
  { id: "doc3", fileName: "1450_grand_concourse_lease_draft.pdf", documentType: "LEASE", fileSize: 512000, mimeType: "application/pdf", fileUrl: "#", uploadedAt: d(3), relatedCaseId: "cs3", relatedCase: { caseNumber: "CASE-2026-003" }, relatedPropertyId: "pr1", relatedProperty: { address: "1450 Grand Concourse", borough: "Bronx" }, relatedContactId: null, relatedContact: null, relatedTenantId: null, relatedTenant: null },
  { id: "doc4", fileName: "robert_chen_hcv_approval.pdf", documentType: "VOUCHER", fileSize: 178000, mimeType: "application/pdf", fileUrl: "#", uploadedAt: d(6), relatedCaseId: "cs7", relatedCase: { caseNumber: "CASE-2026-007" }, relatedPropertyId: null, relatedProperty: null, relatedContactId: "c8", relatedContact: { fullName: "Robert Chen" }, relatedTenantId: null, relatedTenant: null },
  { id: "doc5", fileName: "aisha_jackson_id_docs.pdf", documentType: "ID_DOCUMENT", fileSize: 320000, mimeType: "application/pdf", fileUrl: "#", uploadedAt: d(1), relatedCaseId: "cs2", relatedCase: { caseNumber: "CASE-2026-002" }, relatedPropertyId: null, relatedProperty: null, relatedContactId: "c3", relatedContact: { fullName: "Aisha Jackson" }, relatedTenantId: null, relatedTenant: null },
  { id: "doc6", fileName: "flatbush_apts_hap_contract.pdf", documentType: "HAP_CONTRACT", fileSize: 890000, mimeType: "application/pdf", fileUrl: "#", uploadedAt: d(2), relatedCaseId: "cs5", relatedCase: { caseNumber: "CASE-2026-005" }, relatedPropertyId: "pr6", relatedProperty: { address: "567 Flatbush Ave #1F", borough: "Brooklyn" }, relatedContactId: null, relatedContact: null, relatedTenantId: null, relatedTenant: null },
];

export const MOCK_DASHBOARD_STATS = {
  totalContacts: 47,
  activeTenants: 15,
  availableProperties: 7,
  openCases: 8,
  criticalCases: 3,
  overdueFollowUps: 2,
  missingDocsTenants: 4,
  housedThisMonth: 2,
};

export const MOCK_CASES_BY_STATUS = [
  { status: "SEARCHING", _count: { id: 2 } },
  { status: "NEW", _count: { id: 2 } },
  { status: "VIEWING_SCHEDULED", _count: { id: 2 } },
  { status: "APPLICATION_STARTED", _count: { id: 1 } },
  { status: "LEASE_SIGNING", _count: { id: 1 } },
  { status: "HOUSED", _count: { id: 1 } },
  { status: "CLOSED", _count: { id: 1 } },
];

export const MOCK_PROPERTIES_BY_BOROUGH = [
  { borough: "Brooklyn", _count: { id: 4 } },
  { borough: "Bronx", _count: { id: 3 } },
  { borough: "Queens", _count: { id: 2 } },
  { borough: "Manhattan", _count: { id: 2 } },
  { borough: "Staten Island", _count: { id: 1 } },
];

export const MOCK_VOUCHER_DISTRIBUTION = [
  { voucherSize: 1, _count: { id: 3 } },
  { voucherSize: 2, _count: { id: 7 } },
  { voucherSize: 3, _count: { id: 4 } },
  { voucherSize: 4, _count: { id: 1 } },
];
